import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/cli.ts"],
  format: ["esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  target: "es2022",
  outDir: "dist",
  external: [
    "execa",
    // madge is CJS with dynamic requires - must be external and installed as dependency
    "madge",
    // @typescript-eslint/parser pulls in typescript-estree + debug, which use dynamic
    // require() for Node built-ins ('tty', 'fs', 'path'). Must stay external.
    "@typescript-eslint/parser",
    "@typescript-eslint/visitor-keys",
    "@typescript-eslint/typescript-estree",
    "eslint-visitor-keys",
    // Optional template engines from @vue/compiler-sfc (via madge -> detective-vue2)
    // These are dynamically required and only needed for Vue files using exotic templates
    "velocityjs",
    "dustjs-linkedin",
    "atpl",
    "liquor",
    "twig",
    "ejs",
    "eco",
    "jazz",
    "jqtpl",
    "hamljs",
    "hamlet",
    "whiskers",
    "haml-coffee",
    "hogan.js",
    "templayed",
    "handlebars",
    "underscore",
    "lodash",
    "walrus",
    "mustache",
    "just",
    "ect",
    "mote",
    "toffee",
    "dot",
    "bracket-template",
    "ractive",
    "nunjucks",
    "htmling",
    "babel-core",
    "plates",
    "react-dom/server",
    "react",
    "arc-templates",
    "vash",
    "slm",
    "marko",
    "teacup/lib/express",
    "coffee-script",
    "squirrelly",
    "twing",
  ],
});
