import { MARKETPLACE_INSTALL_VERDICT } from "@/domains/diagnose/checks/marketplace-install";
import { METHODOLOGY_CONTEXT_VERDICT } from "@/domains/diagnose/checks/methodology-context";
import { SESSION_ENVIRONMENT_VERDICT } from "@/domains/diagnose/checks/session-environment";
import { SESSION_STORE_VERDICT } from "@/domains/diagnose/checks/session-store";
import { SPX_REACHABILITY_VERDICT } from "@/domains/diagnose/checks/spx-reachability";
import { WORKTREE_POOL_VERDICT } from "@/domains/diagnose/checks/worktree-pool";
import { CHECK_NAME, type CheckName } from "@/domains/diagnose/manifest";
import { OVERALL_VERDICT, type OverallVerdict, VERDICT_BUCKET, type VerdictBucket } from "@/domains/diagnose/types";
import { SEVERITY, type Severity } from "@/lib/styled-output/styled-output";

/** Source-owned provider verdict domains and the bucket each verdict folds into. */
export const CHECK_VERDICT_BUCKET = {
  [CHECK_NAME.SPX_REACHABILITY]: {
    [SPX_REACHABILITY_VERDICT.REACHABLE]: VERDICT_BUCKET.HEALTHY,
    [SPX_REACHABILITY_VERDICT.PRESENT]: VERDICT_BUCKET.HEALTHY,
    [SPX_REACHABILITY_VERDICT.BELOW_FLOOR]: VERDICT_BUCKET.DEGRADED,
    [SPX_REACHABILITY_VERDICT.UNREACHABLE]: VERDICT_BUCKET.BROKEN,
    [SPX_REACHABILITY_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
  [CHECK_NAME.SESSION_ENVIRONMENT]: {
    [SESSION_ENVIRONMENT_VERDICT.WORKING]: VERDICT_BUCKET.HEALTHY,
    [SESSION_ENVIRONMENT_VERDICT.IDENTITY_ONLY]: VERDICT_BUCKET.DEGRADED,
    [SESSION_ENVIRONMENT_VERDICT.SILENT_NO_OP]: VERDICT_BUCKET.BROKEN,
    [SESSION_ENVIRONMENT_VERDICT.NOT_APPLICABLE]: VERDICT_BUCKET.NOT_APPLICABLE,
    [SESSION_ENVIRONMENT_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
  [CHECK_NAME.WORKTREE_POOL]: {
    [WORKTREE_POOL_VERDICT.COMPLIANT]: VERDICT_BUCKET.HEALTHY,
    [WORKTREE_POOL_VERDICT.NON_COMPLIANT]: VERDICT_BUCKET.BROKEN,
    [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_MISSING]: VERDICT_BUCKET.BROKEN,
    [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_DETACHED]: VERDICT_BUCKET.BROKEN,
    [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_WRONG_BRANCH]: VERDICT_BUCKET.BROKEN,
    [WORKTREE_POOL_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
  [CHECK_NAME.SESSION_STORE]: {
    [SESSION_STORE_VERDICT.CONSISTENT]: VERDICT_BUCKET.HEALTHY,
    [SESSION_STORE_VERDICT.ORPHANED_CLAIMS]: VERDICT_BUCKET.DEGRADED,
    [SESSION_STORE_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
  [CHECK_NAME.MARKETPLACE_INSTALL]: {
    [MARKETPLACE_INSTALL_VERDICT.INSTALLED]: VERDICT_BUCKET.HEALTHY,
    [MARKETPLACE_INSTALL_VERDICT.DRIFTED]: VERDICT_BUCKET.DEGRADED,
    [MARKETPLACE_INSTALL_VERDICT.CLI_UNAVAILABLE]: VERDICT_BUCKET.DEGRADED,
    [MARKETPLACE_INSTALL_VERDICT.UNREGISTERED]: VERDICT_BUCKET.BROKEN,
    [MARKETPLACE_INSTALL_VERDICT.NOT_APPLICABLE]: VERDICT_BUCKET.NOT_APPLICABLE,
    [MARKETPLACE_INSTALL_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
  [CHECK_NAME.METHODOLOGY_CONTEXT]: {
    [METHODOLOGY_CONTEXT_VERDICT.RESOLVED]: VERDICT_BUCKET.HEALTHY,
    [METHODOLOGY_CONTEXT_VERDICT.VERSION_MISMATCH]: VERDICT_BUCKET.DEGRADED,
    [METHODOLOGY_CONTEXT_VERDICT.UNAVAILABLE]: VERDICT_BUCKET.UNKNOWN,
    [METHODOLOGY_CONTEXT_VERDICT.UNKNOWN]: VERDICT_BUCKET.UNKNOWN,
  },
} as const satisfies Readonly<Record<CheckName, Readonly<Record<string, VerdictBucket>>>>;

/** Maps each per-check verdict bucket to the styled-output severity its glyph and color key on. */
export const BUCKET_SEVERITY: Readonly<Record<VerdictBucket, Severity>> = {
  [VERDICT_BUCKET.HEALTHY]: SEVERITY.OK,
  [VERDICT_BUCKET.DEGRADED]: SEVERITY.WARN,
  [VERDICT_BUCKET.UNKNOWN]: SEVERITY.UNKNOWN,
  [VERDICT_BUCKET.BROKEN]: SEVERITY.ERROR,
  [VERDICT_BUCKET.NOT_APPLICABLE]: SEVERITY.MUTED,
} as const;

/** Maps the overall verdict to the styled-output severity its summary line is colored by. */
export const OVERALL_SEVERITY: Readonly<Record<OverallVerdict, Severity>> = {
  [OVERALL_VERDICT.HEALTHY]: SEVERITY.OK,
  [OVERALL_VERDICT.DEGRADED]: SEVERITY.WARN,
  [OVERALL_VERDICT.UNKNOWN]: SEVERITY.UNKNOWN,
  [OVERALL_VERDICT.BROKEN]: SEVERITY.ERROR,
} as const;

export const CANONICAL_CHECKOUT_PROBLEM = {
  [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_DETACHED]: "The designated main checkout is not attached to any branch.",
  [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_MISSING]: "The designated main checkout could not be found.",
  [WORKTREE_POOL_VERDICT.MAIN_CHECKOUT_WRONG_BRANCH]: "The designated main checkout is attached to the wrong branch.",
} as const;

export type CanonicalCheckoutFailureVerdict = keyof typeof CANONICAL_CHECKOUT_PROBLEM;
