export const TEST_RELEVANT_SOURCE_ROOT_PREFIX = {
  SOURCE: "src/",
  TESTING: "testing/",
  SCRIPTS: "scripts/",
  ESLINT_RULES: "eslint-rules/",
} as const;

export const SOURCE_DOMAIN_ROOT_PREFIX = `${TEST_RELEVANT_SOURCE_ROOT_PREFIX.SOURCE}domains/`;

export const TEST_RELEVANT_SOURCE_ROOT_PREFIXES = [
  TEST_RELEVANT_SOURCE_ROOT_PREFIX.SOURCE,
  TEST_RELEVANT_SOURCE_ROOT_PREFIX.TESTING,
  TEST_RELEVANT_SOURCE_ROOT_PREFIX.SCRIPTS,
  TEST_RELEVANT_SOURCE_ROOT_PREFIX.ESLINT_RULES,
] as const;
